### ISSUE TITLE
Otpauth

### ISSUE THREAD

**Issue by mgt16-LANL** [pyscioffice/pyauthenticator#47]
Hi Jan,

I'm getting an error using pyauthenticator - I'm getting the following error attempting to setup a new authentication:

```python
ImportError: cannot import name 'OtpAuth' from 'otpauth' (/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/otpauth/__init__.py)
```

It looks like there's only HOTP and TOTP functions within the otpauth package. This was done with otpauth version 2.1.0 from conda-forge.

Do you know which of these is a good replacement for OtpAuth?

-Michael

**Comment by mgt16-LANL** [comment]
Looks like HOTP was the replacement in v2 for the OtpAuth in v1. For now I'll downgrade otpauth.
https://otp.authlib.org/

**Comment by jan-janssen** [comment]
Can you check your version of the `pyauthenticator`? It should be 0.2.0 as we recently switched from https://github.com/jan-janssen/pyauthenticator/pull/44 `otpauth` to `pyotp`

**Comment by mgt16-LANL** [comment]
I was using 0.0.1 - I believe this was default from conda-forge. Updating to 0.2.0 now!

**Comment by jan-janssen** [comment]
Yes, a couple of things changed in the last month. Is it working now?

**Comment by mgt16-LANL** [comment]
It's working now - but I had to do a quick shuffle of installations.
I had to run:
```bash
mamba uninstall pyzbar
mamba install zbar
mamba install pyzbar
```
After this it worked just fine!

**Comment by jan-janssen** [comment]
Ok, I am a bit confused why conda / mamba messed up the dependencies, hopefully it only affects users upgrading from an older version and the fresh install works fine. I am going to close the issue now, but feel free to reopen it, in case the issue comes up again.

**Comment by jan-janssen** [comment]
@mgt16-LANL I just received an Apple ARM system and recognised that `zbar` was not available for Apple ARM. This is now fixed and with the added support of `zbar` for Apple ARM it is now possible to install `pyauthenticator=0.2.0` on Apple ARM systems.

**Comment by mgt16-LANL** [comment]
Hi @jan-janssen , I installed it in a separate environment I configured to use x86 architecture - https://stackoverflow.com/questions/71515117/how-to-set-up-a-conda-osx-64-environment-on-arm-mac .

**Comment by jan-janssen** [comment]
@mgt16-LANL Sorry, I just realised I made a mistake in the previous comment - it is **now** possible to install `pyauthenticator=0.2.0` in pure Apple ARM environments.
